version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petstoreTrue
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: petstoreTrue
    command: python app.py